# Generated by Django 3.1.11 on 2021-10-13 08:19

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taboobreaker', '0003_auto_20211004_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionform',
            name='ans',
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ans', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('ques', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taboobreaker.questionform')),
            ],
        ),
    ]
