# Generated by Django 3.1.11 on 2021-10-14 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taboobreaker', '0004_auto_20211013_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answered',
            field=models.BooleanField(default=False),
        ),
    ]
