# Generated by Django 3.1.11 on 2021-10-14 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taboobreaker', '0005_answer_answered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='answered',
        ),
        migrations.AddField(
            model_name='questionform',
            name='answered',
            field=models.BooleanField(default=False),
        ),
    ]
